### ISSUE TITLE
classicpres tests always fail

### ISSUE THREAD

**Issue by fingolfin** [hulpke/magmapresentations#3]
... because `tst/testall.g` ends with `FORCE_QUIT_GAP(1);` signalling a failure.

**Comment by olexandr-konovalov** [comment]
... because there are no actual test files in the package.

**Comment by olexandr-konovalov** [comment]
Apologies, should have looked more carefully. `tst/testall.g` is doing this:
```
#
# This file runs package tests. It is also referenced in the package
# metadata in PackageInfo.g.
#
LoadPackage("classicpres");
ReadPackage("classicpres","lib/test.g");
LittleTest();

#TestDirectory(d[1], rec(exitGAP := true,compareFunction:="uptowhitespace"));
#
FORCE_QUIT_GAP(1);
```
So after `LittleTest()` finishes, it reaches `FORCE_QUIT_GAP(1)` and signals failure. One should analyse the result of `LittleTest` and intercept its status.

**Comment by hulpke** [comment]
OH -- the test mechanism is more complicated -- I was trying to save on creating an extra file for one line.
